spiritsword:
  datasource:
    url: jdbc:mysql://192.168.200.129:3306/spiritsword?useSSL=false&serverTimezone=UTC
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  thread:
    core: 5
    max: 10