spiritsword:
  datasource:
    url: jdbc:mysql://192.168.200.129:3306/spiritsword?useSSL=false&serverTimezone=UTC
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  thread:
    core: 5
    max: 10
  scheduler:
    host: 127.0.0.1
    port: 11111
  registry:
    host: 127.0.0.1
    port: 18888
    boss: 1
    worker: 5
    backlog: 128
  task:
    executor:
      worker: 5
